ARG CUDA_VERSION=12.8.2
ARG IMAGE_DISTRO=ubi9

FROM nvidia/cuda:${CUDA_VERSION}-devel-${IMAGE_DISTRO} AS builder

WORKDIR /build
COPY compare.cu gpu_burn-drv.cpp Makefile /build/

RUN make COMPUTE= NVCCFLAGS="-gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_90,code=sm_90 -gencode=arch=compute_100,code=sm_100 -gencode=arch=compute_120,code=sm_120 -gencode=arch=compute_120,code=compute_120"

FROM nvidia/cuda:${CUDA_VERSION}-runtime-${IMAGE_DISTRO}

COPY --from=builder /build/gpu_burn /app/
COPY --from=builder /build/compare.fatbin /app/

WORKDIR /app
LABEL org.opencontainers.image.title="xiaoyi gpu-burn blackwell"
LABEL org.opencontainers.image.description="Native Blackwell sm_100/sm_120 plus recent GPU architectures and compute_120 PTX"

ENTRYPOINT ["./gpu_burn"]
CMD ["60"]
