ARG CUDA_VERSION=11.8.0
ARG IMAGE_DISTRO=ubi8

FROM nvidia/cuda:${CUDA_VERSION}-devel-${IMAGE_DISTRO} AS builder

WORKDIR /build
COPY compare.cu gpu_burn-drv.cpp Makefile /build/

RUN make COMPUTE= NVCCFLAGS="-gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89"

FROM nvidia/cuda:${CUDA_VERSION}-runtime-${IMAGE_DISTRO}

COPY --from=builder /build/gpu_burn /app/
COPY --from=builder /build/compare.fatbin /app/

WORKDIR /app
LABEL org.opencontainers.image.title="xiaoyi gpu-burn universal"
LABEL org.opencontainers.image.description="Native sm_75/sm_80/sm_86/sm_89 with compute_89 PTX fallback"

ENTRYPOINT ["./gpu_burn"]
CMD ["60"]
