"""Persistence contracts used by managers and API services.

SQLite remains the default implementation.  These protocols keep business
services independent from a concrete SQL driver so a MySQL repository can be
introduced without changing task/report/stress orchestration.
"""

from __future__ import annotations

from typing import Any, Protocol


class TaskRepository(Protocol):
    def create_run(
        self,
        metadata: dict[str, Any] | None = None,
        *,
        secret_enc: str = "",
    ) -> dict[str, Any]: ...
    def claim_next(self, stale_after_seconds: float = 120) -> dict[str, Any] | None: ...
    def heartbeat(self, run_id: str) -> None: ...
    def update_progress(self, run_id: str, stage: str, message: str, progress: int) -> None: ...
    def complete(self, run_id: str, run_dir: str = "") -> None: ...
    def fail(self, run_id: str, error: str) -> None: ...
    def add_event(self, run_id: str, level: str, message: str, stage: str = "") -> None: ...
    def add_metric(self, run_id: str, source: str, data: dict[str, Any]) -> None: ...
    def request_stop(self, run_id: str) -> dict[str, Any]: ...
    def is_stop_requested(self, run_id: str) -> bool: ...
    def interrupt(self, run_id: str, message: str = "任务已停止") -> None: ...
    def wake_queued(self, run_id: str) -> dict[str, Any]: ...
    def get_run(self, run_id: str) -> dict[str, Any]: ...
    def list_runs(self, limit: int = 100) -> list[dict[str, Any]]: ...
    def get_events(self, run_id: str, after_id: int = 0, limit: int = 1000) -> list[dict[str, Any]]: ...
    def get_translation_progress_events(self, run_id: str) -> list[dict[str, Any]]: ...
    def get_metrics(self, run_id: str, after_id: int = 0, limit: int = 5000) -> list[dict[str, Any]]: ...


class PlatformRepository(Protocol):
    def count_users(self) -> int: ...
    def count_active_superusers(self) -> int: ...
    def create_user(self, username: str, display_name: str, password_hash: str, *, is_superuser: bool = False, is_active: bool = True) -> dict[str, Any]: ...
    def get_user(self, user_id: str, *, include_password: bool = False) -> dict[str, Any] | None: ...
    def get_user_by_username(self, username: str, *, include_password: bool = False) -> dict[str, Any] | None: ...
    def list_users(self) -> list[dict[str, Any]]: ...
    def update_user(self, user_id: str, **changes: Any) -> dict[str, Any]: ...
    def delete_user(self, user_id: str) -> bool: ...
    def create_project(self, project_key: str, name: str, description: str = "") -> dict[str, Any]: ...
    def get_project(self, project_id: str) -> dict[str, Any] | None: ...
    def list_projects(self, *, include_inactive: bool = True) -> list[dict[str, Any]]: ...
    def update_project(self, project_id: str, **changes: Any) -> dict[str, Any]: ...
    def set_project_membership(self, project_id: str, user_id: str, role: str | None) -> None: ...
    def list_project_members(self, project_id: str) -> list[dict[str, Any]]: ...
    def list_user_projects(self, user_id: str, *, superuser: bool = False) -> list[dict[str, Any]]: ...
    def create_auth_session(self, token_hash: str, user_id: str, csrf_token: str, expires_at: float) -> None: ...
    def get_auth_session(self, token_hash: str) -> dict[str, Any] | None: ...
    def delete_auth_session(self, token_hash: str) -> None: ...
    def add_audit_event(self, **data: Any) -> None: ...
    def list_audit_events(
        self, limit: int = 200, offset: int = 0
    ) -> list[dict[str, Any]]: ...
    def count_audit_events(self) -> int: ...
    def list_server_profiles(self) -> list[dict[str, Any]]: ...
    def get_server_profile(
        self, profile_id: str, *, include_secret: bool = False
    ) -> dict[str, Any] | None: ...
    def save_server_profile(
        self, data: dict[str, Any], credential_enc: str | None
    ) -> dict[str, Any]: ...
    def delete_server_profile(self, profile_id: str) -> bool: ...
    def touch_server_profile(self, profile_id: str) -> None: ...
    def list_model_profiles(self) -> list[dict[str, Any]]: ...
    def get_model_profile(self, profile_id: str) -> dict[str, Any] | None: ...
    def active_model_profile(self) -> dict[str, Any] | None: ...
    def save_model_profile(self, data: dict[str, Any], api_key_enc: str | None) -> dict[str, Any]: ...
    def activate_model(self, profile_id: str) -> None: ...
    def get_report_template(self, version: int | None = None) -> dict[str, Any]: ...
    def save_report_template(self, name: str, sections: list[dict[str, Any]]) -> dict[str, Any]: ...
    def create_report_job(self, run_id: str, template_version: int, options: dict[str, Any]) -> dict[str, Any]: ...
    def get_report_job(self, job_id: str) -> dict[str, Any] | None: ...
    def list_report_jobs(self, limit: int = 100) -> list[dict[str, Any]]: ...
    def claim_report_job(self) -> dict[str, Any] | None: ...
    def complete_report_job(self, job_id: str, snapshot: dict[str, Any], artifacts: dict[str, str]) -> None: ...
    def fail_report_job(self, job_id: str, error: str) -> None: ...
    def create_stress_job(
        self,
        options: dict[str, Any],
        *,
        secret_required: bool = False,
        secret_enc: str = "",
    ) -> dict[str, Any]: ...
    def claim_stress_job(self, excluded_hosts: set[str] | None = None) -> dict[str, Any] | None: ...
    def get_stress_job(self, job_id: str) -> dict[str, Any] | None: ...
    def list_stress_jobs(self, limit: int = 100) -> list[dict[str, Any]]: ...
    def update_stress_job(self, job_id: str, **changes: Any) -> None: ...
    def request_stop_stress_job(self, job_id: str) -> dict[str, Any]: ...
    def is_stress_stop_requested(self, job_id: str) -> bool: ...
    def add_stress_sample(self, job_id: str, source: str, sample: dict[str, Any]) -> None: ...
    def get_stress_samples(self, job_id: str, after_id: int = 0, limit: int = 5000) -> list[dict[str, Any]]: ...
    def save_endpoint_spec(self, data: dict[str, Any], publish: bool = False) -> dict[str, Any]: ...
    def list_endpoint_specs(self, limit: int = 200) -> list[dict[str, Any]]: ...
    def resolve_endpoint(self, default_path: str) -> dict[str, Any] | None: ...
    def list_interface_modules(self, project_id: str) -> list[dict[str, Any]]: ...
    def save_interface_module(self, project_id: str, data: dict[str, Any], module_id: str = "") -> dict[str, Any]: ...
    def delete_interface_module(self, project_id: str, module_id: str) -> bool: ...
    def list_interface_environments(self, project_id: str) -> list[dict[str, Any]]: ...
    def save_interface_environment(self, project_id: str, data: dict[str, Any], environment_id: str = "") -> dict[str, Any]: ...
    def delete_interface_environment(self, project_id: str, environment_id: str) -> bool: ...
    def list_interface_variables(self, project_id: str) -> list[dict[str, Any]]: ...
    def get_interface_variable_records(
        self, project_id: str, environment_id: str = ""
    ) -> list[dict[str, Any]]: ...
    def save_interface_variable(
        self,
        project_id: str,
        data: dict[str, Any],
        variable_id: str = "",
        *,
        secret_enc: str | None = None,
    ) -> dict[str, Any]: ...
    def delete_interface_variable(self, project_id: str, variable_id: str) -> bool: ...
    def list_interface_assets(self, project_id: str, limit: int = 500) -> list[dict[str, Any]]: ...
    def get_interface_asset(self, project_id: str, asset_id: str) -> dict[str, Any] | None: ...
    def save_interface_asset(
        self,
        project_id: str,
        data: dict[str, Any],
        asset_id: str = "",
        *,
        publish: bool = False,
        upsert_by_name: bool = False,
    ) -> dict[str, Any]: ...
    def publish_interface_asset(self, project_id: str, asset_id: str) -> dict[str, Any]: ...
    def delete_interface_asset(self, project_id: str, asset_id: str) -> bool: ...
    def list_interface_asset_versions(self, project_id: str, asset_id: str) -> list[dict[str, Any]]: ...
    def list_interface_scenarios(self, project_id: str, limit: int = 500) -> list[dict[str, Any]]: ...
    def get_interface_scenario(self, project_id: str, scenario_id: str) -> dict[str, Any] | None: ...
    def save_interface_scenario(
        self, project_id: str, data: dict[str, Any], scenario_id: str = ""
    ) -> dict[str, Any]: ...
    def delete_interface_scenario(self, project_id: str, scenario_id: str) -> bool: ...
    def create_interface_scenario_run(
        self,
        project_id: str,
        scenario: dict[str, Any],
        *,
        batch_id: str = "",
        created_by: str = "",
        status: str = "running",
        parameters: dict[str, Any] | None = None,
        concurrency_limit: int = 3,
    ) -> dict[str, Any]: ...
    def claim_interface_scenario_run(self) -> dict[str, Any] | None: ...
    def request_stop_interface_scenario_run(
        self, project_id: str, run_id: str
    ) -> dict[str, Any] | None: ...
    def is_interface_scenario_stop_requested(
        self, project_id: str, run_id: str
    ) -> bool: ...
    def finish_interface_scenario_run(
        self,
        project_id: str,
        run_id: str,
        *,
        status: str,
        summary: dict[str, Any],
        result: dict[str, Any],
        artifacts: dict[str, str] | None = None,
    ) -> dict[str, Any]: ...
    def get_interface_scenario_run(self, project_id: str, run_id: str) -> dict[str, Any] | None: ...
    def list_interface_scenario_runs(self, project_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    def list_interface_scenario_batch_runs(
        self, project_id: str, batch_id: str
    ) -> list[dict[str, Any]]: ...
    def save_model_eval_suite(
        self,
        project_id: str | None,
        data: dict[str, Any],
        suite_id: str = "",
        *,
        created_by: str = "",
    ) -> dict[str, Any]: ...
    def get_model_eval_suite(
        self, project_id: str, suite_id: str, *, include_global: bool = True
    ) -> dict[str, Any] | None: ...
    def list_model_eval_suites(
        self, project_id: str, *, include_global: bool = True, limit: int = 200
    ) -> list[dict[str, Any]]: ...
    def publish_model_eval_suite_version(
        self,
        project_id: str,
        suite_id: str,
        manifest: dict[str, Any],
        cases: list[dict[str, Any]],
        *,
        upstream: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def get_model_eval_suite_version(
        self, project_id: str, version_id: str
    ) -> dict[str, Any] | None: ...
    def list_model_eval_suite_versions(
        self, project_id: str, suite_id: str, limit: int = 100
    ) -> list[dict[str, Any]]: ...
    def list_model_eval_suite_cases(
        self, project_id: str, version_id: str, limit: int = 1000
    ) -> list[dict[str, Any]]: ...
    def create_model_eval_run(
        self,
        project_id: str,
        *,
        model_profile_id: str = "",
        suite_version_id: str = "",
        backend: str = "mock",
        backend_version: str = "",
        snapshot: dict[str, Any] | None = None,
        created_by: str = "",
    ) -> dict[str, Any]: ...
    def claim_model_eval_run(self) -> dict[str, Any] | None: ...
    def update_model_eval_run(
        self,
        run_id: str,
        *,
        status: str | None = None,
        phase: str | None = None,
        progress: int | None = None,
        message: str | None = None,
        summary: dict[str, Any] | None = None,
    ) -> None: ...
    def add_model_eval_run_event(
        self,
        run_id: str,
        event_type: str,
        message: str,
        *,
        phase: str = "",
        progress: int | None = None,
        data: dict[str, Any] | None = None,
    ) -> None: ...
    def request_stop_model_eval_run(
        self, project_id: str, run_id: str
    ) -> dict[str, Any] | None: ...
    def is_model_eval_run_stop_requested(self, run_id: str) -> bool: ...
    def finish_model_eval_run(
        self,
        project_id: str,
        run_id: str,
        *,
        status: str,
        summary: dict[str, Any] | None = None,
        artifact_ref: str = "",
        error: str = "",
    ) -> dict[str, Any]: ...
    def get_model_eval_run(
        self, project_id: str, run_id: str
    ) -> dict[str, Any] | None: ...
    def set_model_eval_run_artifact_ref(
        self, project_id: str, run_id: str, artifact_ref: str
    ) -> dict[str, Any] | None: ...
    def list_model_eval_runs(
        self, project_id: str, limit: int = 100
    ) -> list[dict[str, Any]]: ...
    def delete_model_eval_run(
        self, project_id: str, run_id: str
    ) -> dict[str, Any] | None: ...
    def list_model_eval_run_events(
        self, project_id: str, run_id: str, after_id: int = 0, limit: int = 1000
    ) -> list[dict[str, Any]]: ...
    def save_model_eval_case_results(
        self, project_id: str, run_id: str, results: list[dict[str, Any]]
    ) -> None: ...
    def list_model_eval_case_results(
        self,
        project_id: str,
        run_id: str,
        *,
        offset: int = 0,
        limit: int = 100,
        status: str = "",
    ) -> tuple[list[dict[str, Any]], int]: ...
    def save_model_eval_manual_review(
        self,
        project_id: str,
        run_id: str,
        result_id: str,
        *,
        reviewer_id: str,
        score: dict[str, Any],
        comment: str = "",
    ) -> dict[str, Any]: ...
    def list_model_eval_manual_reviews(
        self, project_id: str, run_id: str, result_id: str = ""
    ) -> list[dict[str, Any]]: ...
    def create_model_eval_comparison(
        self,
        project_id: str,
        run_ids: list[str],
        config: dict[str, Any],
        *,
        created_by: str = "",
    ) -> dict[str, Any]: ...
    def get_model_eval_comparison(
        self, project_id: str, comparison_id: str
    ) -> dict[str, Any] | None: ...
    def list_model_eval_comparisons(
        self, project_id: str, limit: int = 100
    ) -> list[dict[str, Any]]: ...
